29/06/2017 19:18:26 ==> Confirguration Error, check information for objectref=dev0 and groupid=7
29/06/2017 19:51:27 ==> FunctionGetConfigurationStatus:Unhandled exception --Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/06/2017 19:53:02 ==> Function: GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/06/2017 20:07:56 ==> Function: GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
11/07/2017 18:44:26 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
11/07/2017 18:47:21 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
11/07/2017 19:10:21 ==> Function: DYConfig-GetConfigurationStatus : Your request isn't authorized!--Internal exception : , Exception Message: Invalid JSON primitive: ȝ.
11/07/2017 19:11:14 ==> Function: DYConfig-GetConfigurationStatus : Your request isn't authorized!--Internal exception : , Exception Message: Invalid JSON primitive: ȝ.
11/07/2017 19:27:08 ==> Function: DYConfig-GetConfigurationStatus : Your request isn't authorized!--Internal exception : , Exception Message: Invalid JSON primitive: ȝ.
12/07/2017 23:15:01 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
12/07/2017 23:15:38 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Object reference not set to an instance of an object.
12/07/2017 23:16:49 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Object reference not set to an instance of an object.
12/07/2017 23:17:13 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Object reference not set to an instance of an object.
12/07/2017 23:18:45 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Object reference not set to an instance of an object.
14/07/2017 14:56:33 ==> Function: DyAccount-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
14/07/2017 14:58:03 ==> Function: DyAccount-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
14/07/2017 15:01:42 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
14/07/2017 15:03:18 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
20/07/2017 00:40:03 ==> Your request isn't authorized!
20/07/2017 00:45:35 ==> No Chat in queue to publish
03/08/2017 19:49:25 ==> No Chat in queue to publish
03/08/2017 19:51:14 ==> No Chat in queue to publish
03/08/2017 20:35:43 ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: There is already an open DataReader associated with this Connection which must be closed first.
08/08/2017 18:36:01 ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: The entity with a name = 'new_websitealive' was not found in the MetadataCache.
08/08/2017 18:37:40 ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: The entity with a name = 'New_AliveChat' was not found in the MetadataCache.
08/08/2017 18:39:57 ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: 'new_alivechat' entity doesn't contain attribute with Name = 'new_websitealivechat'.
11/08/2017 16:36:50 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 16:43:53 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 16:52:29 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 16:55:03 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 17:02:10 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 17:03:49 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
11/08/2017 22:41:25 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user ''@'tcac-PC' (using password: NO)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket(), Exception Message: Authentication to host '' for user '' using method 'mysql_native_password' failed with message: Access denied for user ''@'tcac-PC' (using password: NO)
11/08/2017 22:41:47 ==> Function: DYConfig-GetConfigurationStatus : Unhandled exception--Internal exception : MySql.Data.MySqlClient.MySqlException (0x80004005): Access denied for user ''@'tcac-PC' (using password: NO)
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.ReadPacket(), Exception Message: Authentication to host '' for user '' using method 'mysql_native_password' failed with message: Access denied for user ''@'tcac-PC' (using password: NO)
11/08/2017 22:46:42 ==> Confirguration Error - Managed solution Not Found, check information
14/08/2017 08:25:04 ==> Confirguration Error - Managed solution Not Found, check information
28/08/2017 10:34:41 ==> Function: DYAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: Invalid URI: The format of the URI could not be determined.
28/08/2017 10:37:28 ==> No Chat in queue to publish
28/08/2017 10:40:12 ==> No Chat in queue to publish
28/08/2017 10:40:39 ==> No Chat in queue to publish
28/08/2017 10:49:32 ==> No Chat in queue to publish
15/09/2017 23:14:16 ==> Function: SalesForceToken-GetAuthorizationToken : Unhandled exception--Internal exception : , Exception Message: expired access/refresh token
15/09/2017 23:15:36 ==> Function: SalesForceToken-GetAuthorizationToken : Unhandled exception--Internal exception : , Exception Message: expired access/refresh token
15/09/2017 23:25:36 ==> Function: SalesForceToken-GetAuthorizationToken : Unhandled exception--Internal exception : , Exception Message: expired access/refresh token
15/09/2017 23:26:38 ==> Function: SalesForceToken-GetAuthorizationToken : Unhandled exception--Internal exception : , Exception Message: expired access/refresh token
15/09/2017 23:29:43 ==> Function: SalesForceToken-GetAuthorizationToken : Unhandled exception--Internal exception : , Exception Message: expired access/refresh token
16/09/2017 00:23:26 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
16/09/2017 00:23:28 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
16/09/2017 00:23:57 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
16/09/2017 00:23:59 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
16/09/2017 00:24:28 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
16/09/2017 00:24:29 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
16/09/2017 00:50:06 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
16/09/2017 00:50:08 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
16/09/2017 01:08:08 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
16/09/2017 01:08:14 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
16/09/2017 01:10:27 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
16/09/2017 01:10:29 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
16/09/2017 01:12:45 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
16/09/2017 01:12:47 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
16/09/2017 01:28:56 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: Unexpected character encountered while parsing value: D. Path '', line 0, position 0.
16/09/2017 01:35:26 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.
16/09/2017 01:36:52 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.
16/09/2017 01:38:57 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: The best overloaded method match for 'Newtonsoft.Json.Linq.JObject.Parse(string)' has some invalid arguments
16/09/2017 01:40:52 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: Error reading JObject from JsonReader. Current JsonReader item is not an object: StartArray. Path '', line 1, position 1.
16/09/2017 01:44:41 ==> System.Collections.Generic.List`1[SalesForceOAuth.Controllers.Account]
25/09/2017 20:05:08 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
25/09/2017 20:05:09 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
25/09/2017 20:16:54 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
25/09/2017 20:16:57 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
25/09/2017 20:24:07 ==> System.Collections.Generic.List`1[SalesForceOAuth.Controllers.Account]
25/09/2017 20:27:53 ==> System.Collections.Generic.List`1[SalesForceOAuth.Controllers.Account]
25/09/2017 20:30:28 ==> System.Collections.Generic.List`1[SalesForceOAuth.Controllers.Account]
25/09/2017 20:32:43 ==> System.Collections.Generic.List`1[SalesForceOAuth.Controllers.Account]
25/09/2017 21:10:19 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Unable to create/update fields: CreatedById. Please check the security settings of this field and verify that it is read/write for your profile or permission set.
25/09/2017 21:13:19 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Unable to create/update fields: CreatedById. Please check the security settings of this field and verify that it is read/write for your profile or permission set.
25/09/2017 21:16:12 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
25/09/2017 21:16:30 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
25/09/2017 21:17:43 ==> Function: SalesForceToken-GetAuthorizationToken : Unhandled exception--Internal exception : , Exception Message: token validity expired
25/09/2017 21:19:44 ==> Function: SalesForceToken-GetAuthorizationToken : Unhandled exception--Internal exception : , Exception Message: token validity expired
25/09/2017 21:27:07 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
25/09/2017 21:27:11 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
25/09/2017 22:00:48 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Operation not valid for this user type
27/09/2017 23:01:13 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Required fields are missing: [LastName, Company]
27/09/2017 23:02:27 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Required fields are missing: [LastName, Company]
27/09/2017 23:10:24 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Required fields are missing: [Company]
27/09/2017 23:43:27 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
27/09/2017 23:43:33 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
28/09/2017 00:02:00 ==> Internal Exception: Related To ID: id value of incorrect type: 00Q0Y000007VGmuUAG
28/09/2017 22:27:39 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
28/09/2017 22:27:41 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
28/09/2017 22:28:05 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
28/09/2017 22:28:59 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
28/09/2017 23:55:25 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
28/09/2017 23:55:28 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
28/09/2017 23:56:17 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
28/09/2017 23:56:42 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
28/09/2017 23:57:01 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
28/09/2017 23:57:55 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
28/09/2017 23:58:42 ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
28/09/2017 23:58:44 ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: token validity expired\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
07/11/2017 14:41:14 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Value cannot be null.
Parameter name: key
07/11/2017 14:41:29 ==> Internal Error: System.TimeoutException: Timeout in IO operation
   at MySql.Data.MySqlClient.TimedStream.StopTimer()
   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
07/11/2017 14:41:32 ==> "Internal Error: System.TimeoutException: Timeout in IO operation\r\n   at MySql.Data.MySqlClient.TimedStream.StopTimer()\r\n   at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)\r\n   at System.IO.BufferedStream.Read(Byte[] array, Int32 offset, Int32 count)\r\n   at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)\r\n   at MySql.Data.MySqlClient.MySqlStream.LoadPacket()\r\n   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()\r\n   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32\u0026 affectedRow, Int64\u0026 insertedId)\r\n   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32\u0026 affectedRows, Int64\u0026 insertedId)\r\n   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)\r\n   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()\r\n   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)"
07/11/2017 14:43:19 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Value cannot be null.
Parameter name: key
07/11/2017 15:09:14 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Value cannot be null.
Parameter name: key
07/11/2017 15:09:17 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Value cannot be null.
Parameter name: key
07/11/2017 15:15:27 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Value cannot be null.
Parameter name: key
07/11/2017 15:15:30 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: No such column 'LeadSubSource' on sobject of type Lead
07/11/2017 15:18:43 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: No such column 'LeadSubSource' on sobject of type Lead
03/12/2017 09:42:04 ==> No Chat in queue to publish
03/12/2017 09:44:00 ==> No Chat in queue to publish
03/12/2017 09:59:41 ==> No Chat in queue to publish
08/12/2017 15:05:57 ==> No Chat in queue to publish
08/12/2017 16:18:14 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
LastName, Company, Email, Phone  (Select ID, Name from Account) 
                                 ^
ERROR at Row:1:Column:56
unexpected token: 'Select'
08/12/2017 16:20:39 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
LastName, Company, Email, Phone  (SELECT ID, Name from Account) 
                                 ^
ERROR at Row:1:Column:56
unexpected token: 'SELECT'
08/12/2017 16:24:33 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
(SELECT ID, Name from Account)  From Contacts where FirstName like '%Nav%'
                                     ^
ERROR at Row:1:Column:93
sObject type 'Contacts' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
08/12/2017 16:25:44 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
ID, Name from Accounts)  From Contacts where FirstName like '%Nav%'
                              ^
ERROR at Row:1:Column:94
sObject type 'Contacts' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
08/12/2017 16:26:38 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
ID, Name from Accounts)  From Contacts where FirstName like '%Nav%'
                              ^
ERROR at Row:1:Column:85
sObject type 'Contacts' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
08/12/2017 16:27:37 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
(SELECT ID, Name from Account)  From Contacts where FirstName like '%Nav%'
                                     ^
ERROR at Row:1:Column:84
sObject type 'Contacts' is not supported. If you are attempting to use a custom object, be sure to append the '__c' after the entity name. Please reference your WSDL or the describe call for the appropriate names.
08/12/2017 16:28:22 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
 Phone, (SELECT ID, Name from Account)  From Contact where FirstName
                              ^
ERROR at Row:1:Column:69
Didn't understand relationship 'Account' in FROM part of query call. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names.
08/12/2017 16:29:27 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
 Phone, (SELECT ID, Name from Accounts)  From Contact where FirstName
                              ^
ERROR at Row:1:Column:69
Didn't understand relationship 'Accounts' in FROM part of query call. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names.
20/12/2017 19:09:57 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
 Phone, (SELECT ID, Name from Accounts)  From Contact where FirstName
                              ^
ERROR at Row:1:Column:69
Didn't understand relationship 'Accounts' in FROM part of query call. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names.
21/12/2017 11:45:29 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
FirstName, LastName, Email, Phone,Account , AccountID, Account.Name
                                  ^
ERROR at Row:1:Column:46
No such column 'Account' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
21/12/2017 11:47:24 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
FirstName, LastName, Email, Phone,Account , AccountID, Account.Name
                                  ^
ERROR at Row:1:Column:46
No such column 'Account' on entity 'Contact'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
21/12/2017 11:51:29 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
 (SELECT AccountID, Name from Account)  From Contact where FirstName
                              ^
ERROR at Row:1:Column:76
Didn't understand relationship 'Account' in FROM part of query call. If you are attempting to use a custom relationship, be sure to append the '__r' after the custom relationship name. Please reference your WSDL or the describe call for the appropriate names.
21/12/2017 11:52:45 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
FirstName, LastName, Email, Phone, from Contact)  From Account) where
                                  ^
ERROR at Row:1:Column:71
unexpected token: 'from'
21/12/2017 12:02:42 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
LastName, Email, Phone From Contact) where FirstName like '%Bates%'
                                  ^
ERROR at Row:1:Column:57
unexpected token: )
21/12/2017 12:03:20 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
Account.Name From Contactwhere FirstName like '%Bates%' OR LastName like
                                        ^
ERROR at Row:1:Column:98
unexpected token: like
21/12/2017 12:16:27 ==> Could not add new contact, check mandatory fields
03/01/2018 19:50:04 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 19:51:21 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 19:58:20 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 20:21:43 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 20:31:52 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 20:32:40 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 20:36:19 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 21:07:13 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 21:07:34 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 21:09:53 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
03/01/2018 21:38:11 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
04/01/2018 15:44:49 ==> Function: DyAccount-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
04/01/2018 15:45:56 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
04/01/2018 16:14:44 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://alive5.crm11.dynamics.com/XRMServices/2011/Organization.svc?wsdl&sdkversion=9'.
04/01/2018 16:27:11 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://alive5.crm11.dynamics.com/XRMServices/2011/Organization.svc?wsdl&sdkversion=9'.
04/01/2018 16:34:42 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://alive5.crm11.dynamics.com/XRMServices/2011/Discovery.svc?wsdl&sdkversion=9'.
04/01/2018 16:45:35 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://alive5.crm11.dynamics.com/XRMServices/2011/Organization.svc?wsdl&sdkversion=9'.
04/01/2018 16:47:01 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://alive5.crm11.dynamics.com/XRMServices/2011/Organization.svc?wsdl&sdkversion=9'.
04/01/2018 16:47:29 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://alive5.crm11.dynamics.com/XRMServices/2011/Organization.svc?wsdl&sdkversion=9'.
04/01/2018 16:49:48 ==> Function: DYLead-GetSearchedLeads : Unhandled exception--Internal exception : System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.TlsStream.CallProcessAuthentication(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://alive5.crm11.dynamics.com/XRMServices/2011/Organization.svc?wsdl&sdkversion=9'.
04/01/2018 17:09:05 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Specified cast is not valid.
04/01/2018 17:10:50 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Specified cast is not valid.
04/01/2018 17:12:39 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Specified cast is not valid.
04/01/2018 17:15:58 ==> Could not add new contact, check mandatory fields
04/01/2018 17:17:49 ==> Could not add new contact, check mandatory fields
04/01/2018 17:18:56 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Specified cast is not valid.
04/01/2018 17:26:05 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Specified cast is not valid.
04/01/2018 17:28:27 ==> Could not add new contact, check mandatory fields
04/01/2018 17:35:55 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Specified cast is not valid.
04/01/2018 17:40:13 ==> Could not add new contact, check mandatory fields
04/01/2018 17:41:02 ==> Could not add new contact, check mandatory fields
04/01/2018 17:50:19 ==> Could not add new contact, check mandatory fields
24/01/2018 23:33:19 ==> Function: DYContacts-GetSearchedContacts : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
24/01/2018 23:34:02 ==> Function: DYContacts-GetSearchedContacts : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
26/02/2018 13:52:49 ==> Function: SFLeads-GetSearchedLeads : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
26/02/2018 13:58:25 ==> Function: SFLeads-GetSearchedLeads : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
26/02/2018 14:00:21 ==> Function: SFLeads-GetSearchedLeads : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
26/02/2018 14:28:36 ==> Function: SFContacts-GetSearchedContacts : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
27/02/2018 12:15:05 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: 
Phone like '%eyJ0eXAiOiJK%' OR Description like '%eyJ0eXAiOiJK%'
                               ^
ERROR at Row:1:Column:104
field 'Description' can not be filtered in a query call
27/02/2018 12:30:58 ==> Function: DYAccounts-GetSearchedAccounts : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
27/02/2018 12:33:53 ==> Function: DYAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: ID3242: The security token could not be authenticated or authorized.
27/02/2018 12:36:48 ==> Function: DYAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: ID3242: The security token could not be authenticated or authorized.
27/02/2018 13:41:22 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
27/02/2018 14:11:21 ==> Function: DYAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: ID3242: The security token could not be authenticated or authorized.
27/02/2018 14:13:20 ==> Function: DYAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: ID3242: The security token could not be authenticated or authorized.
28/02/2018 23:34:04 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Unknown column 'scs.search_field_name' in 'field list'
28/02/2018 23:34:57 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Unknown column 'scs.search_field_name' in 'field list'
28/02/2018 23:36:48 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
Phone like '%eyJ0eXAiOiJK%' OR Title|Source like '%eyJ0eXAiOiJK%' OR
                                   ^
ERROR at Row:1:Column:206
unexpected token: '|'
28/02/2018 23:37:16 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
Title like '%eyJ0eXAiOiJK%' OR Source like '%eyJ0eXAiOiJK%'
                               ^
ERROR at Row:1:Column:233
No such column 'Source' on entity 'Lead'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
05/03/2018 23:09:30 ==> function hit: no problem there
06/03/2018 00:22:18 ==> function hit: no problem there
06/03/2018 00:23:05 ==> User not registered to use this application.
06/03/2018 00:24:37 ==> function hit: no problem there
07/03/2018 18:40:43 ==> function hit: no problem there
08/03/2018 21:22:26 ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : System.Net.WebException: The remote name could not be resolved: 'websitealive4.onmicrosoft.com'
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://websitealive4.onmicrosoft.com//XRMServices/2011/Organization.svc?wsdl&sdkversion=9'.
08/03/2018 21:22:58 ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : System.Net.WebException: The remote name could not be resolved: 'websitealive4.onmicrosoft.com'
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://websitealive4.onmicrosoft.com//XRMServices/2011/Organization.svc?wsdl&sdkversion=9'.
08/03/2018 21:24:30 ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : System.Net.WebException: The remote name could not be resolved: 'websitealive4.onmicrosoft.com'
   at System.Net.HttpWebRequest.GetResponse()
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataLocationRetriever.DownloadMetadata(TimeoutHelper timeoutHelper)
   at System.ServiceModel.Description.MetadataExchangeClient.MetadataRetriever.Retrieve(TimeoutHelper timeoutHelper), Exception Message: Metadata contains a reference that cannot be resolved: 'https://websitealive4.onmicrosoft.com//XRMServices/2011/Organization.svc?wsdl&sdkversion=9'.
08/03/2018 21:29:28 ==> Confirguration Error - Managed solution Not Found, check information
19/03/2018 20:38:41 ==> function hit: no problem there
19/03/2018 21:00:17 ==> reading exception: helper get access token issue
19/03/2018 21:00:19 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Cannot perform runtime binding on a null reference
19/03/2018 21:07:25 ==> reading exception: helper get access token issue
19/03/2018 21:07:26 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 'System.Dynamic.ExpandoObject' does not contain a definition for 'Add'
19/03/2018 21:12:05 ==> reading exception: helper get access token issue
19/03/2018 21:12:17 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 'System.Dynamic.ExpandoObject' does not contain a definition for 'Add'
19/03/2018 21:24:43 ==> reading exception: helper get access token issue
19/03/2018 21:24:45 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 'System.Dynamic.ExpandoObject' does not contain a definition for 'Add'
20/03/2018 14:21:40 ==> reading exception: helper get access token issue
20/03/2018 14:21:40 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT * From Lead where FirstName like
      ^
ERROR at Row:1:Column:7
unexpected token: '*'
20/03/2018 14:22:34 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT * From Lead where FirstName like
      ^
ERROR at Row:1:Column:7
unexpected token: '*'
20/03/2018 15:08:27 ==> Function: SFContacts-GetSearchedContacts : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
20/03/2018 15:45:47 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: 
OR Fax like '%eyJ0eXAiOiJK%' OR Description like '%eyJ0eXAiOiJK%'
                                ^
ERROR at Row:1:Column:165
field 'Description' can not be filtered in a query call
20/03/2018 15:46:09 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: 
OR Fax like '%eyJ0eXAiOiJK%' OR Description like '%eyJ0eXAiOiJK%'
                                ^
ERROR at Row:1:Column:165
field 'Description' can not be filtered in a query call
20/03/2018 15:47:02 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: 
OR Fax like '%eyJ0eXAiOiJK%' OR Description like '%eyJ0eXAiOiJK%'
                                ^
ERROR at Row:1:Column:165
field 'Description' can not be filtered in a query call
20/03/2018 15:48:37 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: 
OR Fax like '%eyJ0eXAiOiJK%' OR Description like '%eyJ0eXAiOiJK%'
                                ^
ERROR at Row:1:Column:165
field 'Description' can not be filtered in a query call
20/03/2018 15:48:52 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: 
OR Fax like '%eyJ0eXAiOiJK%' OR Description like '%eyJ0eXAiOiJK%'
                                ^
ERROR at Row:1:Column:165
field 'Description' can not be filtered in a query call
20/03/2018 16:33:24 ==> Function: DYContacts-GetSearchedContacts : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
20/03/2018 16:34:34 ==> Function: DYContacts-GetSearchedContacts : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
20/03/2018 16:35:37 ==> Function: DYAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: Unknown column 'i.ObjectRef' in 'where clause'
20/03/2018 16:42:33 ==> Function: SFAccount-PostAccount : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
20/03/2018 19:04:20 ==> Function: SFAccount-GetSearchedAccounts : Unhandled exception--Internal exception : , Exception Message: 
OR Fax like '%eyJ0eXAiOiJK%' OR Description like '%eyJ0eXAiOiJK%'
                                ^
ERROR at Row:1:Column:165
field 'Description' can not be filtered in a query call
21/03/2018 16:38:05 ==> Internal Exception: No such column 'type' on sobject of type Task
21/03/2018 16:46:37 ==> Internal Exception: Call Type: bad value for restricted picklist field: Chat -Online
21/03/2018 17:40:48 ==> Function: SFContacts-GetSearchedContacts : Your request isn't authorized!--Internal exception : , Exception Message: Token must consist from 3 delimited by dot parts
21/03/2018 17:43:29 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT Id  from Account where Id like '%00Q0Y000007Va42UAC%'
                              ^
ERROR at Row:1:Column:31
invalid operator on id field
21/03/2018 17:43:52 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT Id  from Account where Id like '%00Q0Y000007Va42UAC%'
                              ^
ERROR at Row:1:Column:31
invalid operator on id field
21/03/2018 17:45:27 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
 Email, Phone from lead where Id like '%00Q0Y000007Va42UAC%'
                              ^
ERROR at Row:1:Column:72
invalid operator on id field
21/03/2018 17:47:39 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
 Phone from lead where Id like =00Q0Y000007Va42UAC
                              ^
ERROR at Row:1:Column:79
Bind variables only allowed in Apex code
21/03/2018 22:56:33 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
21/03/2018 22:58:49 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
21/03/2018 23:00:11 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
21/03/2018 23:01:00 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
21/03/2018 23:04:58 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
21/03/2018 23:07:07 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
21/03/2018 23:07:24 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
21/03/2018 23:13:49 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
27/03/2018 18:40:13 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'Name'
27/03/2018 18:43:34 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'Name'
27/03/2018 20:38:36 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: only aggregate expressions use field aliasing
27/03/2018 20:50:49 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT Id, , Title FirstName, LastName, Email
          ^
ERROR at Row:1:Column:11
unexpected token: ','
29/03/2018 12:55:57 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/03/2018 13:08:23 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/03/2018 13:22:39 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/03/2018 13:25:24 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
29/03/2018 13:26:11 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/03/2018 13:27:58 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/03/2018 13:32:09 ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
29/03/2018 13:37:26 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
29/03/2018 14:24:07 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Object reference not set to an instance of an object.
29/03/2018 14:29:48 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:entity. The InnerException message was 'Error in line 1 position 8564. Element 'http://schemas.datacontract.org/2004/07/System.Collections.Generic:value' contains data from a type that maps to the name 'Microsoft.Xrm.Tooling.Connector:CrmDataTypeWrapper'. The deserializer has no knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'CrmDataTypeWrapper' and namespace 'Microsoft.Xrm.Tooling.Connector'.'.  Please see InnerException for more details.
29/03/2018 15:06:33 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:entity. The InnerException message was 'Error in line 1 position 8910. Element 'http://schemas.datacontract.org/2004/07/System.Collections.Generic:value' contains data from a type that maps to the name 'Microsoft.Xrm.Tooling.Connector:CrmDataTypeWrapper'. The deserializer has no knowledge of any type that maps to this name. Consider changing the implementation of the ResolveName method on your DataContractResolver to return a non-null value for name 'CrmDataTypeWrapper' and namespace 'Microsoft.Xrm.Tooling.Connector'.'.  Please see InnerException for more details.
29/03/2018 15:24:35 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Incorrect attribute value type System.String
29/03/2018 15:32:07 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Incorrect attribute value type System.String
29/03/2018 15:32:39 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Incorrect attribute value type System.String
29/03/2018 15:33:45 ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Input string was not in a correct format.
13/04/2018 22:35:14 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Phone number not in right format
02/05/2018 21:59:34 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Index was outside the bounds of the array.
02/05/2018 22:00:17 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Index was outside the bounds of the array.
02/05/2018 22:03:25 ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Index was outside the bounds of the array.
23/05/2018 11:39:34 ==> Function: Salesforce-GetRedirectURL : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
23/05/2018 11:40:16 ==> Function: Salesforce-GetRedirectURL : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
23/05/2018 11:40:33 ==> Function: Salesforce-GetRedirectURL : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
23/05/2018 11:47:29 ==> Function: Salesforce-GetRedirectURL : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
25/05/2018 16:43:04 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Account ID: id value of incorrect type: 0010Y0000
25/05/2018 16:45:33 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Account ID: id value of incorrect type: 0010Y0000
25/05/2018 16:45:53 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Account ID: id value of incorrect type: 0010Y0000
25/05/2018 16:50:50 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Account ID: id value of incorrect type: 0010Y000002c2Rm2
25/05/2018 16:51:49 ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Account ID: id value of incorrect type: 0010Y000002c2Rm2
6/6/2018 10:45:03 AM ==> Internal Error: 
6/6/2018 10:46:21 AM ==> "Internal Error: "
6/6/2018 10:51:19 AM ==> Internal Error: 
6/6/2018 10:51:19 AM ==> "Internal Error: "
6/6/2018 11:12:43 AM ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts.
6/6/2018 11:12:44 AM ==> "Unhandled exception--Internal exception : , Exception Message: Unable to connect to any of the specified MySQL hosts."
6/6/2018 1:12:50 PM ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: User
6/6/2018 1:57:55 PM ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
6/6/2018 2:08:21 PM ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
6/6/2018 2:11:20 PM ==> Internal Exception: Dynamics setup is incomplete or login credentials are not right. 
6/6/2018 2:21:19 PM ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
6/6/2018 2:24:12 PM ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
6/6/2018 2:31:32 PM ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Organization cannot be null or empty.
Parameter name: Organization Name
6/6/2018 2:56:00 PM ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: 'contact' entity doesn't contain attribute with Name = 'ayu_salesperson' and NameMapping = 'Logical'.
6/6/2018 3:01:04 PM ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: 'contact' entity doesn't contain attribute with Name = 'ayu_salesperson' and NameMapping = 'Logical'.
6/6/2018 3:10:19 PM ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: User
6/6/2018 3:36:23 PM ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: An item with the same key has already been added.
6/6/2018 3:38:21 PM ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: An item with the same key has already been added.
6/6/2018 3:42:23 PM ==> Function: DyLead-PostLead : Unhandled exception--Internal exception : , Exception Message: An item with the same key has already been added.
6/6/2018 3:56:28 PM ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: 'contact' entity doesn't contain attribute with Name = 'ayu_salesperson' and NameMapping = 'Logical'.
6/7/2018 9:57:32 AM ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Invalid URI: The format of the URI could not be determined.
6/7/2018 9:58:55 AM ==> Function: DyContact-GetConfigurationStatus : Unhandled exception--Internal exception : , Exception Message: Invalid URI: The format of the URI could not be determined.
6/7/2018 2:04:49 PM ==> Function: DyAccount-PostAccount : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
6/7/2018 2:05:53 PM ==> Function: DyAccount-PostAccount : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
6/7/2018 2:51:34 PM ==> No Chat in queue to publish
6/7/2018 2:52:46 PM ==> No Chat in queue to publish
6/7/2018 2:59:37 PM ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: Byte array for GUID must be exactly 16 bytes long.
6/19/2018 10:56:35 AM ==> Function: SFAccount-PostAccount : Your request isn't authorized!--Internal exception : , Exception Message: Token has expired.
6/19/2018 11:01:05 AM ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: retry your request
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
6/19/2018 11:01:05 AM ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: retry your request\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
6/19/2018 11:02:54 AM ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: retry your request
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
6/19/2018 11:02:54 AM ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: retry your request\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
6/19/2018 12:23:36 PM ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: retry your request
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
6/19/2018 12:23:36 PM ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: retry your request\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
6/19/2018 12:24:25 PM ==> Function: SalesForce-GetAccessToken : Unhandled exception--Internal exception : Salesforce.Common.ForceException: retry your request
   at Salesforce.Common.AuthenticationClient.<TokenRefreshAsync>d__13.MoveNext(), Exception Message: One or more errors occurred.
6/19/2018 12:24:30 PM ==> "Unhandled exception--Internal exception : Salesforce.Common.ForceException: retry your request\r\n   at Salesforce.Common.AuthenticationClient.\u003cTokenRefreshAsync\u003ed__13.MoveNext(), Exception Message: One or more errors occurred."
6/19/2018 12:35:41 PM ==> Function: SFAccount-PostAccount : Unhandled exception--Internal exception : , Exception Message: Cannot deserialize instance of date from VALUE_STRING value 6/30/2018 or request may be missing a required field at [line:1, column:60]
6/20/2018 3:29:36 PM ==> SalesForce Error: The Account either Business or Personal
6/20/2018 3:31:19 PM ==> SalesForce Error: The Account either Business or Personal
6/20/2018 3:33:35 PM ==> SalesForce Error: The Account either Business or Personal
6/20/2018 3:36:47 PM ==> SalesForce Error: The Account either Business or Personal
6/20/2018 3:40:58 PM ==> SalesForce Error: Invalid AccountType for Business Account the AccountType is 0 & for Personal Account AccountType is 1
6/21/2018 11:40:20 AM ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: 'ayu_alivechat' entity doesn't contain attribute with Name = 'gol_leadid' and NameMapping = 'Logical'.
6/21/2018 11:42:59 AM ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: 'ayu_alivechat' entity doesn't contain attribute with Name = 'gol_leadid' and NameMapping = 'Logical'.
6/22/2018 11:06:49 AM ==> Function: SFChat-PostChat : Unhandled exception--Internal exception : , Exception Message: Lead With Id = 4357974b-e275-e811-a95d-000d3a33efbc Does Not Exist
6/26/2018 9:51:32 AM ==> SalesForce Error: Invalid AccountType. For Business Account the AccountType is 0 and for Personal Account AccountType is 1
6/26/2018 10:33:20 AM ==> Function: SFAccount-PostAccount : Unhandled exception--Internal exception : , Exception Message: Required fields are missing: [Name]
6/28/2018 9:57:26 AM ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: No such column 'FieldName' on sobject of type Lead
6/28/2018 10:12:05 AM ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: No such column 'test' on sobject of type Lead
6/28/2018 10:14:51 AM ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: No such column 'test' on sobject of type Lead
6/28/2018 10:18:14 AM ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: No such column 'test' on sobject of type Lead
6/28/2018 10:22:08 AM ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: An element with the same key 'Title' already exists in the ExpandoObject.
6/28/2018 10:42:20 AM ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Value cannot be null.
Parameter name: key
6/28/2018 12:58:03 PM ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: No such column 'test' on sobject of type Lead
6/28/2018 3:16:24 PM ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Email: invalid email address: raja.goldevelopers.com
6/28/2018 3:17:55 PM ==> Function: SFLead-PostLead : Unhandled exception--Internal exception : , Exception Message: Email: invalid email address: raja.goldevelopers.com
7/3/2018 12:23:03 PM ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Could not find specified column in results: entity_type
7/3/2018 12:23:55 PM ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: Could not find specified column in results: entity_type
7/3/2018 12:40:49 PM ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT Id , pacid__c, Title, pacid__c, FirstName, LastName, Company
                             ^
ERROR at Row:1:Column:30
duplicate field selected: pacid__c
7/3/2018 12:42:30 PM ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT Id , pacid__c, Title, pacid__c, FirstName, LastName, Company
                             ^
ERROR at Row:1:Column:30
duplicate field selected: pacid__c
7/3/2018 12:43:28 PM ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT Id , pacid__c, Title, pacid__c, FirstName, LastName, Company
                             ^
ERROR at Row:1:Column:30
duplicate field selected: pacid__c
7/3/2018 12:44:38 PM ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT Id , pacid__c, Title, pacid__c, FirstName, LastName, Company
                             ^
ERROR at Row:1:Column:30
duplicate field selected: pacid__c
7/3/2018 12:55:54 PM ==> Function: SFLead-GetSearchedLeads : Unhandled exception--Internal exception : , Exception Message: 
SELECT Id , pacid__c, Title, pacid__c, FirstName, LastName, Company
                             ^
ERROR at Row:1:Column:30
duplicate field selected: pacid__c
